target 'ZiZaiTianProject' do
pod 'MJExtension'
pod 'AFNetworking'
pod 'CDDPagerController'
pod 'SDWebImage', '~> 4.0'
pod 'BAPickView'
pod ‘UMengAnalytics’
pod ‘JGProgressHUD’
pod ‘UITableView+FDTemplateLayoutCell’
pod ‘MJRefresh’
pod ‘Masonry’
pod 'UITableView+FDTemplateLayoutCell'
end

